<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Program;

class ProgramSeeder extends Seeder
{
    public function run(): void
    {
        $programs = [
            // International Preschool
            [
                'name' => 'Pre-Nursery',
                'level' => 'international-preschool',
                'category' => 'Preschool',
                'slug' => 'International Preschool - Pre-Nursery',
                'image' => 'img/preschool.png',
                'slogan' => 'A Gentle First Step into Learning',
                'description' => 'Our Pre-Nursery program introduces young learners to a safe, nurturing, and stimulating environment where they begin exploring the world through play, sensory activities, and early social interaction. This program focuses on emotional security, independence, and joyful learning experiences.',
            ],
            [
                'name' => 'Nursery',
                'level' => 'international-preschool',
                'category' => 'Preschool',
                'slug' => 'International Preschool - Nursery',
                'image' => 'img/preschool.png',
                'slogan' => 'Building Confidence Through Play',
                'description' => 'The Nursery program supports children in developing communication, motor skills, and social awareness through structured play and hands-on activities. Our curriculum encourages curiosity, self-expression, and a love for learning in a warm and supportive environment.',
            ],
            [
                'name' => 'Kindergarten 1',
                'level' => 'international-preschool',
                'category' => 'Preschool',
                'slug' => 'International Preschool - Kindergarten1',
                'image' => 'img/preschool.png',
                'slogan' => 'Learning to Explore and Express',
                'description' => 'Kindergarten 1 focuses on developing early literacy, numeracy, and creative thinking skills. Children are encouraged to explore ideas, express themselves confidently, and build strong learning habits through engaging and meaningful activities.',
            ],
            [
                'name' => 'Kindergarten 2',
                'level' => 'international-preschool',
                'category' => 'Preschool',
                'slug' => 'International Preschool - Kindergarten2',
                'image' => 'img/preschool.png',
                'slogan' => 'Growing Independence and Responsibility',
                'description' => 'In Kindergarten 2, children strengthen academic readiness while developing independence and responsibility. The program nurtures problem-solving skills, collaboration, and confidence, preparing learners for more structured learning experiences.',
            ],
            [
                'name' => 'Kindergarten 3',
                'level' => 'international-preschool',
                'category' => 'Preschool',
                'slug' => 'International Preschool - Kindergarten3',
                'image' => 'img/preschool.png',
                'slogan' => 'Preparing Confident Learners for the Future',
                'description' => 'Kindergarten 3 prepares children for primary school by enhancing academic skills, critical thinking, and social-emotional development. This program builds confident, curious, and independent learners ready to take their next educational journey.',
            ],
            [
                'name' => 'Family Engagement',
                'level' => 'international-preschool',
                'category' => 'Preschool',
                'slug' => 'International Preschool - Family',
                'image' => 'img/preschool.png',
                'slogan' => 'Learning Together, Growing Together',
                'description' => 'The Family Engagement program encourages active collaboration between school and families. Through guided activities, parenting resources, and home-learning support, this program empowers parents to actively participate in their child’s learning journey at home.',
            ],


            // Child Development
            [
                'name' => 'Psychology and Behaviour Support',
                'level' => 'child-development',
                'category' => 'Child Dev',
                'slug' => 'Child Development - 1',
                'image' => 'img/child_develop.jpg',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Speech and Occupational Therapy',
                'level' => 'child-development',
                'category' => 'Child Dev',
                'slug' => 'Child Development - 2',
                'image' => 'img/child_develop.jpg',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Health and Nutrition Guidance',
                'level' => 'child-development',
                'category' => 'Child Dev',
                'slug' => 'Child Development - 3',
                'image' => 'img/child_develop.jpg',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Parenting Consultation and Support',
                'level' => 'child-development',
                'category' => 'Child Dev',
                'slug' => 'Child Development - 4',
                'image' => 'img/child_develop.jpg',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Early Financial Literacy',
                'level' => 'child-development',
                'category' => 'Child Dev',
                'slug' => 'Child Development - 5',
                'image' => 'img/child_develop.jpg',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Sensory and Enrichment Program',
                'level' => 'child-development',
                'category' => 'Child Dev',
                'slug' => 'Child Development - 6',
                'image' => 'img/child_develop.jpg',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Drama and Public Speaking',
                'level' => 'child-development',
                'category' => 'Child Dev',
                'slug' => 'Child Development - 7',
                'image' => 'img/child_develop.jpg',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Academic and Cognitive Support',
                'level' => 'child-development',
                'category' => 'Child Dev',
                'slug' => 'Child Development - 8',
                'image' => 'img/child_develop.jpg',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Child Development Trial',
                'level' => 'child-development',
                'category' => 'Child Dev',
                'slug' => 'Child Development - Trial',
                'image' => 'img/child_develop.jpg',
                'slogan' => '',
                'description' => '',
            ],

            // English
            [
                'name' => 'Very Young Learners English',
                'level' => 'english-very-young-learners',
                'category' => 'English',
                'slug' => 'Very Young Learners English',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            //
            [
                'name' => 'English Brave Starter',
                'level' => 'english-young-learners',
                'category' => 'English',
                'slug' => 'English - Brave Starter',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'English Super Movers',
                'level' => 'english-young-learners',
                'category' => 'English',
                'slug' => 'English - Super Movers',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'English Fearless Flyers',
                'level' => 'english-young-learners',
                'category' => 'English',
                'slug' => 'English - Fearless Flyers',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            //
            [
                'name' => 'English Seeker',
                'level' => 'english-teenagers',
                'category' => 'English',
                'slug' => 'English - Seeker',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'English Explorer',
                'level' => 'english-teenagers',
                'category' => 'English',
                'slug' => 'English - Explorer',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'English Adventurer',
                'level' => 'english-teenagers',
                'category' => 'English',
                'slug' => 'English - Adventurer',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'English Voyager',
                'level' => 'english-teenagers',
                'category' => 'English',
                'slug' => 'English - Voyager',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'English Connector',
                'level' => 'english-teenagers',
                'category' => 'English',
                'slug' => 'English - Connector',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'English Elit',
                'level' => 'english-teenagers',
                'category' => 'English',
                'slug' => 'English - Elite',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'English Legend',
                'level' => 'english-teenagers',
                'category' => 'English',
                'slug' => 'English - Legend',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            //
            [
                'name' => 'English Skillful Foundation',
                'level' => 'english-adults',
                'category' => 'English',
                'slug' => 'English - Skillful Foundation',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'English Adult Level 1',
                'level' => 'english-adults',
                'category' => 'English',
                'slug' => 'English - Level 1',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'English Adult Level 2',
                'level' => 'english-adults',
                'category' => 'English',
                'slug' => 'English - Level 2',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'English Adult Level 3',
                'level' => 'english-adults',
                'category' => 'English',
                'slug' => 'English - Level 3',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            //
            [
                'name' => 'Ready for IELTS',
                'level' => 'exam-prep',
                'category' => 'English',
                'slug' => 'English - Exam Preparation',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            //
            [
                'name' => 'English International Business',
                'level' => 'business',
                'category' => 'English',
                'slug' => 'English - International Business',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'English Trial',
                'level' => 'english-trial',
                'category' => 'English',
                'slug' => 'English - Trial',
                'image' => 'img/english.png',
                'slogan' => '',
                'description' => '',
            ],

            // Mandarin
            [
                'name' => 'Mandarin Little Panda',
                'level' => 'mandarin-young-learners',
                'category' => 'Mandarin',
                'slug' => 'Mandarin - Little Panda',
                'image' => 'img/mandarin.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Mandarin Smart Panda',
                'level' => 'mandarin-young-learners',
                'category' => 'Mandarin',
                'slug' => 'Mandarin - Smart Panda',
                'image' => 'img/mandarin.png',
                'slogan' => '',
                'description' => '',
            ],
            //
            [
                'name' => 'Mandarin Discoverer',
                'level' => 'mandarin-teenagers',
                'category' => 'Mandarin',
                'slug' => 'Mandarin - Discorverer',
                'image' => 'img/mandarin.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Mandarin Explorer',
                'level' => 'mandarin-teenagers',
                'category' => 'Mandarin',
                'slug' => 'Mandarin - Explorer',
                'image' => 'img/mandarin.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Mandarin Navigator',
                'level' => 'mandarin-teenagers',
                'category' => 'Mandarin',
                'slug' => 'Mandarin - Navigator',
                'image' => 'img/mandarin.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Mandarin Achiever',
                'level' => 'mandarin-teenagers',
                'category' => 'Mandarin',
                'slug' => 'Mandarin - Achiever',
                'image' => 'img/mandarin.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Mandarin Master',
                'level' => 'mandarin-teenagers',
                'category' => 'Mandarin',
                'slug' => 'Mandarin - Master',
                'image' => 'img/mandarin.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Mandarin Elite',
                'level' => 'mandarin-teenagers',
                'category' => 'Mandarin',
                'slug' => 'Mandarin - Elite',
                'image' => 'img/mandarin.png',
                'slogan' => '',
                'description' => '',
            ],
            //
            [
                'name' => 'Business Mandarin Foundation',
                'level' => 'mandarin-adults',
                'category' => 'Mandarin',
                'slug' => 'Business Mandarin Foundation',
                'image' => 'img/mandarin.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Corporate Mandarin',
                'level' => 'mandarin-adults',
                'category' => 'Mandarin',
                'slug' => 'Corporate Mandarin',
                'image' => 'img/mandarin.png',
                'slogan' => '',
                'description' => '',
            ],
            //
            [
                'name' => 'HSK Test Preparation',
                'level' => 'mandarin-specialized',
                'category' => 'Mandarin',
                'slug' => 'HSK Test Preparation',
                'image' => 'img/mandarin.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Business Chinese Certificate',
                'level' => 'mandarin-specialized',
                'category' => 'Mandarin',
                'slug' => 'Business Chinese Certificate',
                'image' => 'img/mandarin.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Mandarin Trial',
                'level' => 'mandarin-trial',
                'category' => 'Mandarin',
                'slug' => 'Mandarin - Trial',
                'image' => 'img/mandarin.png',
                'slogan' => '',
                'description' => '',
            ],
            

            // Math
            [
                'name' => 'Math Explorer',
                'level' => 'math-level1',
                'category' => 'Math',
                'slug' => 'Math - Explorer',
                'image' => 'img/math.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Math Operation Heroes',
                'level' => 'math-level2',
                'category' => 'Math',
                'slug' => 'Math - Operation Heroes',
                'image' => 'img/math.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Math Challenge Champions',
                'level' => 'math-level3',
                'category' => 'Math',
                'slug' => 'Math - Challenge Champions',
                'image' => 'img/math.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Math Mavericks',
                'level' => 'math-level4',
                'category' => 'Math',
                'slug' => 'Math - Mavericks',
                'image' => 'img/math.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Math Trial',
                'level' => 'math-trial',
                'category' => 'Math',
                'slug' => 'Math - Trial',
                'image' => 'img/math.png',
                'slogan' => '',
                'description' => '',
            ],


            // STREAM
            [
                'name' => 'Junior Coder',
                'level' => 'pathway1',
                'category' => 'Coding',
                'slug' => 'STREAM - Junior Code',
                'image' => 'img/robotic.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Code Adventure',
                'level' => 'pathway2',
                'category' => 'Coding',
                'slug' => 'STREAM - Code Adventure',
                'image' => 'img/robotic.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Python Developer',
                'level' => 'pathway3',
                'category' => 'Coding',
                'slug' => 'STREAM - Python Developer',
                'image' => 'img/robotic.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Software Developer ',
                'level' => 'pathway4',
                'category' => 'Coding',
                'slug' => 'STREAM - Software Developer ',
                'image' => 'img/robotic.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'AI Engineer ',
                'level' => 'pathway5',
                'category' => 'Coding',
                'slug' => 'STREAM - AI Engineer ',
                'image' => 'img/robotic.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'STREAM Trial',
                'level' => 'stream-trial',
                'category' => 'Coding',
                'slug' => 'STREAM - Trial ',
                'image' => 'img/robotic.png',
                'slogan' => '',
                'description' => '',
            ],


            // Design
            [
                'name' => 'Kids Animation Basics',
                'level' => 'design-kids',
                'category' => 'Design',
                'slug' => 'Design - Kids Animation Basics',
                'image' => 'img/design.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Kids Advanced Animation',
                'level' => 'design-kids',
                'category' => 'Design',
                'slug' => 'Design - Kids Advanced Animation',
                'image' => 'img/design.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Branding Kids',
                'level' => 'design-kids',
                'category' => 'Design',
                'slug' => 'Design - Branding Kids',
                'image' => 'img/design.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Kids UI/UX Design',
                'level' => 'design-kids',
                'category' => 'Design',
                'slug' => 'Design - Kids UI/UX',
                'image' => 'img/design.png',
                'slogan' => '',
                'description' => '',
            ],
            //
            [
                'name' => 'Teens Design Basics',
                'level' => 'design-teens',
                'category' => 'Design',
                'slug' => 'Basics Design - Teens',
                'image' => 'img/design.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Teens Branding Design',
                'level' => 'design-teens',
                'category' => 'Design',
                'slug' => 'Branding Design - Teens',
                'image' => 'img/design.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Teens UI/UX Design',
                'level' => 'design-teens',
                'category' => 'Design',
                'slug' => 'Design - Teens UI/UX',
                'image' => 'img/design.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Teens Animation Basics',
                'level' => 'design-teens',
                'category' => 'Design',
                'slug' => 'Design - Teens Animation Basics',
                'image' => 'img/design.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Teens Advanced Animation',
                'level' => 'design-teens',
                'category' => 'Design',
                'slug' => 'Design - Teens Advanced Animation ',
                'image' => 'img/design.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Design Trial',
                'level' => 'design-trial',
                'category' => 'Design',
                'slug' => 'Design - Trial ',
                'image' => 'img/design.png',
                'slogan' => '',
                'description' => '',
            ],

            // SkillLab
            [
                'name' => 'Life SkillLab Workshop',
                'level' => 'skill-workshop',
                'category' => 'Life SKill',
                'slug' => 'Life SKill - Workshop',
                'image' => 'img/coding.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Financial Literacy',
                'level' => 'skill-workshop',
                'category' => 'Life SKill',
                'slug' => 'Financial Literacy Bootcamp',
                'image' => 'img/coding.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Public Speaking & Communication Mastery',
                'level' => 'skill-workshop',
                'category' => 'Life SKill',
                'slug' => 'Public Speaking & Communication Mastery',
                'image' => 'img/coding.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Leadership & Team Dynamics',
                'level' => 'skill-workshop',
                'category' => 'Life SKill',
                'slug' => 'Leadership & Team Dynamics',
                'image' => 'img/coding.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'AI & Entrepreneurship Innovation',
                'level' => 'skill-workshop',
                'category' => 'Life SKill',
                'slug' => 'AI & Entrepreneurship Innovation',
                'image' => 'img/coding.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Art & Engineering Fusion',
                'level' => 'skill-workshop',
                'category' => 'Life SKill',
                'slug' => 'Art & Engineering Fusion',
                'image' => 'img/coding.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Discipline Dojo',
                'level' => 'skill-workshop',
                'category' => 'Life SKill',
                'slug' => 'Discipline Dojo',
                'image' => 'img/coding.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Life Skill Trial',
                'level' => 'skill-trial',
                'category' => 'Life SKill',
                'slug' => 'Life Skill - Trial',
                'image' => 'img/coding.png',
                'slogan' => '',
                'description' => '',
            ],


            // Architect
            [
                'name' => 'Young Architects',
                'level' => 'architect-level1',
                'category' => 'Architect',
                'slug' => 'Young Architects',
                'image' => 'img/architec.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Design Explorers',
                'level' => 'architect-level2',
                'category' => 'Architect',
                'slug' => 'Design Explorers',
                'image' => 'img/architec.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Urban Innovators',
                'level' => 'architect-level3',
                'category' => 'Architect',
                'slug' => 'Urban Innovators',
                'image' => 'img/architec.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Future Architects',
                'level' => 'architect-level4',
                'category' => 'Architect',
                'slug' => 'Future Architects',
                'image' => 'img/architec.png',
                'slogan' => '',
                'description' => '',
            ],
            [
                'name' => 'Architects Trial',
                'level' => 'architect-trial',
                'category' => 'Architect',
                'slug' => 'Architects - Trial',
                'image' => 'img/architec.png',
                'slogan' => '',
                'description' => '',
            ],

            // Parenting 
            [
                'name' => 'Parenting Life Indonesia',
                'level' => 'parenting-life',
                'category' => 'Parenting',
                'slug' => 'Parenting Life',
                'image' => 'img/parenting.jpg',
                'slogan' => 'Be the Best Kind of Parent You can Be',
                'description' => 'You can consult with professional counselors and coaches about personal issues, relationship problems, child development, and various other life issues.',
            ],
        ];

        foreach ($programs as $program) {
            Program::create([
                'name' => $program['name'],
                'level' => $program['level'],
                'category' => $program['category'],
                'slug' => $program['slug'],
                'image' => $program['image'],
                'slogan' => $program['slogan'],
                'description' => $program['description'],
            ]);
        }
    }
}
